blueprint:
  name: deCONZ - Aqara Magic Cube MFKZQ01LM
  description: Control anything using Aqara Magic Cube
  domain: automation
  input:
    remote:
      name: Remote
      description: Magic Cube to use
      selector:
        device:
          integration: deconz
          manufacturer: LUMI
    current_face:
      name: Current face helper (1–6)
      description: Optional helper that stores which face is up (1–6). Used for per-face rotation actions.
      default: null
      selector:
        entity:
          multiple: false
          domain:
            - input_number
            - input_text
    wake:
      name: Cube wake up
      description: Action to run when cube wakes
      default: []
      selector:
        action: {}
    slide:
      name: Slide the cube
      description: Action to run on slide movement
      default: []
      selector:
        action: {}
    double_tap:
      name: Double tap the cube
      description: Action to run on a double tap
      default: []
      selector:
        action: {}
    flip_180:
      name: Flip the cube 180 degrees
      description: Action to run on a 180 flip
      default: []
      selector:
        action: {}
    flip_90:
      name: Flip the cube 90 degrees
      description: Action to run on a 90 flip
      default: []
      selector:
        action: {}
    shake:
      name: Shake the cube
      description: Action to run when the cube is shaked
      default: []
      selector:
        action: {}
    drop:
      name: Drop the cube
      description: Action to run when the cube is dropped
      default: []
      selector:
        action: {}
    rotate_cw:
      name: Rotate cube clockwise
      description: Action to run when the cube is rotated clockwise
      default: []
      selector:
        action: {}
    rotate_ccw:
      name: Rotate cube counter clockwise
      description: Action to run when the cube is rotated counter clockwise
      default: []
      selector:
        action: {}
    rotate_cw_face_1:
      name: Rotate CW with face 1 up
      description: Action to run when rotating clockwise and face 1 is up
      default: []
      selector:
        action: {}
    rotate_cw_face_2:
      name: Rotate CW with face 2 up
      description: Action to run when rotating clockwise and face 2 is up
      default: []
      selector:
        action: {}
    rotate_cw_face_3:
      name: Rotate CW with face 3 up
      description: Action to run when rotating clockwise and face 3 is up
      default: []
      selector:
        action: {}
    rotate_cw_face_4:
      name: Rotate CW with face 4 up
      description: Action to run when rotating clockwise and face 4 is up
      default: []
      selector:
        action: {}
    rotate_cw_face_5:
      name: Rotate CW with face 5 up
      description: Action to run when rotating clockwise and face 5 is up
      default: []
      selector:
        action: {}
    rotate_cw_face_6:
      name: Rotate CW with face 6 up
      description: Action to run when rotating clockwise and face 6 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_1:
      name: Rotate CCW with face 1 up
      description: Action to run when rotating counter clockwise and face 1 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_2:
      name: Rotate CCW with face 2 up
      description: Action to run when rotating counter clockwise and face 2 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_3:
      name: Rotate CCW with face 3 up
      description: Action to run when rotating counter clockwise and face 3 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_4:
      name: Rotate CCW with face 4 up
      description: Action to run when rotating counter clockwise and face 4 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_5:
      name: Rotate CCW with face 5 up
      description: Action to run when rotating counter clockwise and face 5 is up
      default: []
      selector:
        action: {}
    rotate_ccw_face_6:
      name: Rotate CCW with face 6 up
      description: Action to run when rotating counter clockwise and face 6 is up
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/deconz-xiaomi-aqara-mfkzq01lm-cube-controller/255988
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'remote'
action:
- variables:
    event: '{{ trigger.event.data.event }}'
    face_entity: !input 'current_face'
    face_state: >-
      {{
        face_entity is not none
        and
        (
          (states(face_entity) | int(0))
          if face_entity.split('.') | first == 'input_number'
          else (states(face_entity) | int(0))
        )
        or 0
      }}
- choose:
  - conditions:
    - '{{ event == 7000 }}'
    sequence: !input 'wake'
  - conditions:
    - '{{ event in [1000, 2000, 3000, 4000, 5000, 6000] }}'
    sequence: !input 'slide'
  - conditions:
    - '{{ event in [1001, 2002, 3003, 4004, 5005, 6006] }}'
    sequence: !input 'double_tap'
  - conditions:
    - '{{ event in [1006, 2005, 3004, 4003, 5002, 6001] }}'
    sequence:
    - variables:
        new_face: '{{ (event | int) % 10 }}'
    - choose:
      - conditions:
        - '{{ face_entity is not none }}'
        - '{{ face_entity.split(".") | first == "input_number" }}'
        sequence:
        - service: input_number.set_value
          data:
            value: '{{ new_face }}'
          target:
            entity_id: '{{ face_entity }}'
      - conditions:
        - '{{ face_entity is not none }}'
        - '{{ face_entity.split(".") | first == "input_text" }}'
        sequence:
        - service: input_text.set_value
          data:
            value: '{{ new_face }}'
          target:
            entity_id: '{{ face_entity }}'
      default: []
    - sequence: !input 'flip_180'
  - conditions:
    - '{{ event in [1002, 1003, 1004, 1005, 2001, 2003, 2004, 2006, 3001, 3002, 3005,
      3006, 4001, 4002, 4005, 4006, 5001, 5003, 5004, 5006, 6002, 6003, 6004, 6005] }}'
    sequence:
    - variables:
        new_face: '{{ (event | int) % 10 }}'
    - choose:
      - conditions:
        - '{{ face_entity is not none }}'
        - '{{ face_entity.split(".") | first == "input_number" }}'
        sequence:
        - service: input_number.set_value
          data:
            value: '{{ new_face }}'
          target:
            entity_id: '{{ face_entity }}'
      - conditions:
        - '{{ face_entity is not none }}'
        - '{{ face_entity.split(".") | first == "input_text" }}'
        sequence:
        - service: input_text.set_value
          data:
            value: '{{ new_face }}'
          target:
            entity_id: '{{ face_entity }}'
      default: []
    - sequence: !input 'flip_90'
  - conditions:
    - '{{ event == 7007 }}'
    sequence: !input 'shake'
  - conditions:
    - '{{ event == 7008 }}'
    sequence: !input 'drop'
  - conditions:
    - '{{ event | int > 0 }}'
    sequence:
    - choose:
      - conditions:
        - '{{ face_state == 1 }}'
        sequence: !input 'rotate_cw_face_1'
      - conditions:
        - '{{ face_state == 2 }}'
        sequence: !input 'rotate_cw_face_2'
      - conditions:
        - '{{ face_state == 3 }}'
        sequence: !input 'rotate_cw_face_3'
      - conditions:
        - '{{ face_state == 4 }}'
        sequence: !input 'rotate_cw_face_4'
      - conditions:
        - '{{ face_state == 5 }}'
        sequence: !input 'rotate_cw_face_5'
      - conditions:
        - '{{ face_state == 6 }}'
        sequence: !input 'rotate_cw_face_6'
      default: !input 'rotate_cw'
  - conditions:
    - '{{ event | int < 0 }}'
    sequence:
    - choose:
      - conditions:
        - '{{ face_state == 1 }}'
        sequence: !input 'rotate_ccw_face_1'
      - conditions:
        - '{{ face_state == 2 }}'
        sequence: !input 'rotate_ccw_face_2'
      - conditions:
        - '{{ face_state == 3 }}'
        sequence: !input 'rotate_ccw_face_3'
      - conditions:
        - '{{ face_state == 4 }}'
        sequence: !input 'rotate_ccw_face_4'
      - conditions:
        - '{{ face_state == 5 }}'
        sequence: !input 'rotate_ccw_face_5'
      - conditions:
        - '{{ face_state == 6 }}'
        sequence: !input 'rotate_ccw_face_6'
      default: !input 'rotate_ccw'